/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContextEmpty: typeof import('./../components/ContextEmpty.vue')['default']
    CustomerButton: typeof import('./../components/CustomerButton.vue')['default']
    FaultPersonSelect: typeof import('./../components/FaultPersonSelect.vue')['default']
    FaultTypePicker: typeof import('./../components/FaultTypePicker.vue')['default']
    HomeTabbar: typeof import('./../components/HomeTabbar.vue')['default']
    ImgLine: typeof import('./../components/ImgLine.vue')['default']
    OrderCreateContext: typeof import('./../components/OrderCreateContext.vue')['default']
    OrderList: typeof import('./../components/OrderList.vue')['default']
    OrderListItem: typeof import('./../components/OrderListItem.vue')['default']
    OrderSearch: typeof import('./../components/OrderSearch.vue')['default']
    OrderStatus: typeof import('./../components/OrderStatus.vue')['default']
    OrderStatusSelect: typeof import('./../components/OrderStatusSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextLine: typeof import('./../components/TextLine.vue')['default']
  }
}
